#pragma once

enum XOCEAN_STAT
{
    XOCEAN_STAT_OK = 0,
    XOCEAN_STAT_NOT_IMPLEMENTED,
    XOCEAN_STAT_NOT_SUPPORTED,
    XOCEAN_STAT_NOT_FOUND,
    XOCEAN_STAT_INVALID_ARGUMENT,
    XOCEAN_STAT_INVALID_STATE,
    XOCEAN_STAT_INVALID_OPERATION,
    XOCEAN_STAT_OUT_OF_MEMORY,
    XOCEAN_STAT_NOT_INITIALIZED,
    XOCEAN_STAT_UNKNOWN,
    XOCEAN_STAT_BAD_PATH,

};
