#pragma once

#define QO_LIB_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define QO_LIB_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define QO_LIB_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define QO_LIB_BUILD_TIMESTAMP @PROJECT_BUILD_TIMESTAMP@